<a href="https://colab.research.google.com/github/cpython-projects/python_da_17_03_26/blob/main/lesson_23.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Легенда

Ви — аналітик даних у роздрібній компанії, що розвиває мобільний застосунок. Команда продукту хоче зрозуміти:

* як користувачі взаємодіють із застосунком: скільки установок, скільки переглядають товари, скільки купують;
* де втрачаються користувачі (на якому етапі воронки);
* яка ефективність різних каналів залучення.

## Таблиці бази даних

**1. `app_sessions`** — установки застосунку

| Поле                  | Тип SQL        | Опис                                            |
| --------------------- | -------------- | ----------------------------------------------- |
| `session_id`          | `VARCHAR(20)`  | Унікальний ідентифікатор установки              |
| `device_code`         | `VARCHAR(20)`  | Ідентифікатор пристрою                          |
| `first_seen`          | `DATE`         | Дата установки                                  |
| `os_type`             | `VARCHAR(10)`  | Платформа (`iOS`, `Android`)                    |
| `acquisition_channel` | `VARCHAR(50)`  | Канал установки (`Organic`, `Facebook` і т.д.)  |
| `cpi_uah`             | `NUMERIC(6,2)` | Вартість установки (Cost Per Install) у гривнях |

> `cpi_uah` (Cost Per Install) — це сума, яку компанія платить рекламній платформі (наприклад, Facebook, Google Ads) за те, що користувач встановив застосунок по рекламі.
> * Використовується для оцінки ефективності каналів і розрахунку окупності (ROI)

---

**2. `product_views_log`** — перегляди товарів

| Поле          | Тип SQL       | Опис                           |
| ------------- | ------------- | ------------------------------ |
| `device_code` | `VARCHAR(20)` | Пристрій                       |
| `view_date`   | `DATE`        | Дата перегляду                 |
| `platform`    | `VARCHAR(10)` | Платформа                      |
| `view_count`  | `INTEGER`     | Кількість переглянутих товарів |

---

**3. `devices_users_map`** — відповідність `device_code` і `user_uuid`

| Поле          | Тип SQL       | Опис                                 |
| ------------- | ------------- | ------------------------------------ |
| `device_code` | `VARCHAR(20)` | Пристрій                             |
| `user_uuid`   | `VARCHAR(20)` | Користувач (присвоюється при логіні) |

> Користувач може не авторизуватися — тоді `user_uuid` відсутній.

---

**4. `orders_log`** — покупки

| Поле         | Тип SQL         | Опис                                     |
| ------------ | --------------- | ---------------------------------------- |
| `user_uuid`  | `VARCHAR(20)`   | Унікальний ID авторизованого користувача |
| `order_time` | `DATE`          | Дата замовлення                          |
| `total_uah`  | `NUMERIC(10,2)` | Сума покупки у гривнях                   |

## Зв’язки таблиць

| Зв’язок                                                    | Опис                             |
| ---------------------------------------------------------- | -------------------------------- |
| `app_sessions.device_code = devices_users_map.device_code` | Зв’язок установки з користувачем |
| `devices_users_map.user_uuid = orders_log.user_uuid`       | Хто зробив замовлення            |
| `product_views_log.device_code = app_sessions.device_code` | Хто переглядав товари            |

## Шлях користувача

```
ВСТАНОВИВ → ПЕРЕГЛЯДАВ → АВТОРИЗУВАВСЯ → КУПИВ
(app_sessions) → (product_views_log) → (devices_users_map) → (orders_log)
```

## SQL-запити для створення таблиць

```sql
DROP TABLE IF EXISTS orders_log;
DROP TABLE IF EXISTS devices_users_map;
DROP TABLE IF EXISTS product_views_log;
DROP TABLE IF EXISTS app_sessions;

CREATE TABLE app_sessions (
    session_id VARCHAR(10) PRIMARY KEY,
    device_code VARCHAR(20) UNIQUE,
    first_seen DATE,
    os_type VARCHAR(10),
    acquisition_channel VARCHAR(50),
    cpi_uah NUMERIC(6, 2)
);

CREATE TABLE product_views_log (
    device_code VARCHAR(20),
    view_date DATE,
    platform VARCHAR(10),
    view_count INTEGER,
    FOREIGN KEY (device_code) REFERENCES app_sessions(device_code)
);

CREATE TABLE devices_users_map (
    device_code VARCHAR(20),
    user_uuid VARCHAR(20) UNIQUE,
    FOREIGN KEY (device_code) REFERENCES app_sessions(device_code)
);

CREATE TABLE orders_log (
    user_uuid VARCHAR(20),
    order_time DATE,
    total_uah NUMERIC(10, 2),
    FOREIGN KEY (user_uuid) REFERENCES devices_users_map(user_uuid)
);
```

In [1]:
## Підключення до бази даних

DB_USER = "prog_academy_da_157g_user"
DB_PASSWORD = "XTE8IHOEtQZ5GasTkaOjcGMKYTha6LeO"
DB_HOST = "dpg-d8t957gg4nts73da5bg0-a.frankfurt-postgres.render.com"
DB_PORT = "5432"
DB_NAME = "prog_academy_da_157g"

In [2]:
url = f"postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"

In [3]:
url

'postgresql://prog_academy_da_157g_user:XTE8IHOEtQZ5GasTkaOjcGMKYTha6LeO@dpg-d8t957gg4nts73da5bg0-a.frankfurt-postgres.render.com:5432/prog_academy_da_157g'

In [4]:
!pip install sqlalchemy

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.50)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)

In [5]:
from sqlalchemy import create_engine

engine = create_engine(url)

In [6]:
from sqlalchemy import inspect

In [7]:
inspector = inspect(engine)
inspector.get_table_names()

['app_sessions', 'product_views_log', 'devices_users_map', 'orders_log']

## SELECT, FROM, WHERE — основа SQL-запиту

Кожен SQL-запит починається з чіткої структури:

```sql
SELECT [що вибрати]
FROM [звідки взяти]
WHERE [які рядки відфільтрувати]
```

### SELECT

* Вказує, **які стовпці** ми хочемо отримати
* Можна вказати `*`, щоб взяти всі стовпці (на практиці — лише для відладки)
* Підтримує **вирази** (арифметика, функції, перейменування через `AS`)

> ❗ **Порядок рядків не гарантований!**
> Якщо важливий порядок — використовуйте `ORDER BY`

### FROM

* Обов’язково вказує, **з якої таблиці** брати дані
* Може бути не одна таблиця (пізніше буде `JOIN`)

### WHERE

* Фільтрація рядків до всіх інших операцій (до `GROUP BY`, `HAVING`)
* Працює лише з рядками, які **існують** у таблиці

> ❗ **WHERE не може використовувати агрегатні функції** (наприклад, `AVG()`)

In [8]:
import pandas as pd

In [9]:
query = """
SELECT *
FROM app_sessions
"""

df = pd.read_sql(query, engine)

In [10]:
df

    session_id device_code  first_seen  os_type acquisition_channel  cpi_uah
0       S00000     DVC0000  2024-04-25  Android            Facebook    30.53
1       S00001     DVC0001  2024-01-15  Android            Referral    13.91
2       S00002     DVC0002  2024-01-18  Android            Facebook    31.80
3       S00003     DVC0003  2024-02-23      iOS            Referral    14.98
4       S00004     DVC0004  2024-04-24  Android          Google Ads    29.64
..         ...         ...         ...      ...                 ...      ...
495     S00495     DVC0495  2024-06-20      iOS             Organic    19.58
496     S00496     DVC0496  2024-02-08  Android          Google Ads    34.12
497     S00497     DVC0497  2024-01-10  Android            Referral    20.56
498     S00498     DVC0498  2024-02-11  Android             Organic    27.31
499     S00499     DVC0499  2024-05-07      iOS          Google Ads    39.78

[500 rows x 6 columns]

In [11]:
df.columns.to_list()

['session_id',
 'device_code',
 'first_seen',
 'os_type',
 'acquisition_channel',
 'cpi_uah']

In [14]:
query = """
SELECT session_id, device_code, cpi_uah * 1.2 AS cpi_podatok_uah
FROM app_sessions
"""

df = pd.read_sql(query, engine)
df

    session_id device_code  cpi_podatok_uah
0       S00000     DVC0000           36.636
1       S00001     DVC0001           16.692
2       S00002     DVC0002           38.160
3       S00003     DVC0003           17.976
4       S00004     DVC0004           35.568
..         ...         ...              ...
495     S00495     DVC0495           23.496
496     S00496     DVC0496           40.944
497     S00497     DVC0497           24.672
498     S00498     DVC0498           32.772
499     S00499     DVC0499           47.736

[500 rows x 3 columns]

In [18]:
query = """
SELECT session_id, device_code, cpi_uah * 1.2 AS cpi_podatok_uah
FROM app_sessions
WHERE cpi_uah > 30
"""

df = pd.read_sql(query, engine)
df

    session_id device_code  cpi_podatok_uah
0       S00000     DVC0000           36.636
1       S00002     DVC0002           38.160
2       S00006     DVC0006           36.672
3       S00010     DVC0010           39.360
4       S00011     DVC0011           37.884
..         ...         ...              ...
156     S00489     DVC0489           42.096
157     S00492     DVC0492           37.692
158     S00493     DVC0493           36.552
159     S00496     DVC0496           40.944
160     S00499     DVC0499           47.736

[161 rows x 3 columns]

## Приклад небезпечного коду (SQL-ін’єкція)

Цей запит буде:

```sql
SELECT * FROM app_sessions
WHERE first_seen >= '2024-03-01' OR '1'='1'
```

`OR '1'='1'` завжди істинне, отже фільтр `first_seen >= ...` не працює — повертаються всі рядки, що небезпечно.

## Безпечний параметризований запит

## Логічні оператори AND, OR, IN, BETWEEN, LIKE

* `AND`, `OR` — дозволяють об’єднувати умови
* `AND` — обидві частини мають бути істинними
* `OR` — достатньо, щоб одна була істинною

> **Використовуйте дужки!** Логіка без дужок може бути несподіваною

### Приклад використання AND

In [20]:
query = """
SELECT session_id, device_code, cpi_uah
FROM app_sessions
WHERE cpi_uah > 30 AND os_type = 'Android'
"""

df = pd.read_sql(query, engine)
df

   session_id device_code  cpi_uah
0      S00000     DVC0000    30.53
1      S00002     DVC0002    31.80
2      S00011     DVC0011    31.57
3      S00013     DVC0013    37.82
4      S00021     DVC0021    39.72
..        ...         ...      ...
93     S00486     DVC0486    31.48
94     S00488     DVC0488    30.11
95     S00492     DVC0492    31.41
96     S00493     DVC0493    30.46
97     S00496     DVC0496    34.12

[98 rows x 3 columns]

### Оператор IN

Спрощує множинні порівняння (альтернатива багатьом OR)

In [21]:
query = """
SELECT session_id, device_code, acquisition_channel
FROM app_sessions
WHERE acquisition_channel IN ('Google', 'Facebook')
"""

df = pd.read_sql(query, engine)
df

    session_id device_code acquisition_channel
0       S00000     DVC0000            Facebook
1       S00002     DVC0002            Facebook
2       S00005     DVC0005            Facebook
3       S00010     DVC0010            Facebook
4       S00012     DVC0012            Facebook
..         ...         ...                 ...
129     S00486     DVC0486            Facebook
130     S00487     DVC0487            Facebook
131     S00490     DVC0490            Facebook
132     S00493     DVC0493            Facebook
133     S00494     DVC0494            Facebook

[134 rows x 3 columns]

### BETWEEN a AND b

Діапазон значень включно. Зручно для дат і чисел

In [22]:
query = """
SELECT session_id, device_code, acquisition_channel
FROM app_sessions
WHERE first_seen BETWEEN '2024-01-01' AND '2024-02-01'
"""

df = pd.read_sql(query, engine)
df

   session_id device_code acquisition_channel
0      S00001     DVC0001            Referral
1      S00002     DVC0002            Facebook
2      S00008     DVC0008          Google Ads
3      S00024     DVC0024          Google Ads
4      S00034     DVC0034             Organic
..        ...         ...                 ...
89     S00472     DVC0472            Facebook
90     S00476     DVC0476            Referral
91     S00483     DVC0483          Google Ads
92     S00490     DVC0490            Facebook
93     S00497     DVC0497            Referral

[94 rows x 3 columns]

### LIKE — пошук за шаблоном

* `%` — будь-яка кількість будь-яких символів
* `_` — один будь-який символ

---

### Особливості LIKE у PostgreSQL

* `LIKE` — **чутливий до регістру**
* Для нечутливого пошуку використовуйте `ILIKE`

---

### Приклади LIKE:

| Умова          | Знайде рядки, де...              |
| -------------- | -------------------------------- |
| `LIKE 'Alex%'` | починається з `Alex`             |
| `LIKE '%son'`  | закінчується на `son`            |
| `LIKE '%lex%'` | містить `lex` у будь-якому місці |
| `LIKE '%'`     | всі рядки                        |

---

### Приклад регістронезалежного пошуку:

```sql
SELECT * FROM products
WHERE name ILIKE '%phone%';
```

---

### Символ `_` у LIKE

| Умова         | Знайде                              |
| ------------- | ----------------------------------- |
| `LIKE '_ex'`  | `Lex`, `Rex`, але не `Alex`         |
| `LIKE 'A__x'` | `Alex`, `Abbx`, але не `Ax`, `Alx` |

In [28]:
from sqlalchemy import text

query = text("""
SELECT session_id, device_code, acquisition_channel
FROM app_sessions
WHERE acquisition_channel LIKE '%o%'
""")

df = pd.read_sql(query, engine)
df

    session_id device_code acquisition_channel
0       S00000     DVC0000            Facebook
1       S00002     DVC0002            Facebook
2       S00004     DVC0004          Google Ads
3       S00005     DVC0005            Facebook
4       S00008     DVC0008          Google Ads
..         ...         ...                 ...
252     S00490     DVC0490            Facebook
253     S00493     DVC0493            Facebook
254     S00494     DVC0494            Facebook
255     S00496     DVC0496          Google Ads
256     S00499     DVC0499          Google Ads

[257 rows x 3 columns]

## ORDER BY, LIMIT

* `ORDER BY` — сортування результату
* За замовчуванням — за зростанням (`ASC`)
* Можна вказати `DESC` — за спаданням
* `LIMIT` — обмежує кількість рядків (часто з `ORDER BY` для топ-N)

In [29]:
from sqlalchemy import text

query = text("""
SELECT session_id, device_code, acquisition_channel, cpi_uah
FROM app_sessions
ORDER BY cpi_uah DESC
LIMIT 5
""")

In [30]:
df = pd.read_sql(query, engine)
df

  session_id device_code acquisition_channel  cpi_uah
0     S00108     DVC0108          Google Ads    40.00
1     S00186     DVC0186            Referral    39.95
2     S00445     DVC0445             Organic    39.89
3     S00499     DVC0499          Google Ads    39.78
4     S00041     DVC0041            Facebook    39.77

## IS NULL — робота з пропущеними значеннями

* `NULL` — "нічого" або "невідомо"
* Порівнювати `= NULL` не можна, треба `IS NULL` або `IS NOT NULL`

COALESCE(назва_стовпчика, 0) + 1  
NULL AND TRUE -> NULL

## DISTINCT — видалення дублікатів

* Видаляє повні дублікати рядків
* Працює на всю комбінацію стовпців, а не на окремі

In [32]:
query = text("""
SELECT DISTINCT acquisition_channel
FROM app_sessions
""")

df = pd.read_sql(query, engine)
df

  acquisition_channel
0             Organic
1            Referral
2            Facebook
3          Google Ads

## Задачі

In [33]:
!pip install sqlalchemy

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.50)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)

In [34]:
import pandas as pd
from sqlalchemy import create_engine, text

In [35]:
DB_USER = "prog_academy_da_157g_user"
DB_PASSWORD = "XTE8IHOEtQZ5GasTkaOjcGMKYTha6LeO"
DB_HOST = "dpg-d8t957gg4nts73da5bg0-a.frankfurt-postgres.render.com"
DB_PORT = "5432"
DB_NAME = "prog_academy_da_157g"

In [36]:
url = f"postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"

In [37]:
engine = create_engine(url)

**Задача 1.** Знайти всі установки з лютого 2024 року по каналах `'Organic'` або `'Referral'`.

In [41]:
query = text("""
SELECT *
FROM app_sessions
WHERE first_seen >= '2024-02-01' AND acquisition_channel IN ('Organic', 'Referral')
""")

df = pd.read_sql(query, engine)
df

    session_id device_code  first_seen  os_type acquisition_channel  cpi_uah
0       S00003     DVC0003  2024-02-23      iOS            Referral    14.98
1       S00006     DVC0006  2024-03-02      iOS            Referral    30.56
2       S00007     DVC0007  2024-05-25      iOS             Organic    15.28
3       S00009     DVC0009  2024-05-05  Android            Referral    21.54
4       S00011     DVC0011  2024-03-25  Android             Organic    31.57
..         ...         ...         ...      ...                 ...      ...
194     S00489     DVC0489  2024-05-29      iOS            Referral    35.08
195     S00491     DVC0491  2024-05-28      iOS            Referral    27.90
196     S00492     DVC0492  2024-04-21  Android             Organic    31.41
197     S00495     DVC0495  2024-06-20      iOS             Organic    19.58
198     S00498     DVC0498  2024-02-11  Android             Organic    27.31

[199 rows x 6 columns]

**Задача 2.** Вивести топ-5 найдорожчих установок за `cpi_uah`.

In [44]:
query = text("""
SELECT *
FROM app_sessions
ORDER BY cpi_uah DESC
LIMIT 5
""")

df = pd.read_sql(query, engine)
df

  session_id device_code  first_seen  os_type acquisition_channel  cpi_uah
0     S00108     DVC0108  2024-02-29  Android          Google Ads    40.00
1     S00186     DVC0186  2024-04-14  Android            Referral    39.95
2     S00445     DVC0445  2024-04-27  Android             Organic    39.89
3     S00499     DVC0499  2024-05-07      iOS          Google Ads    39.78
4     S00041     DVC0041  2024-06-27      iOS            Facebook    39.77

**Задача 3.** Знайти унікальні платформи, на які встановлювали застосунок.

In [45]:
query = text("""
SELECT DISTINCT os_type
FROM app_sessions
""")

df = pd.read_sql(query, engine)
df

   os_type
0      iOS
1  Android

**Задача 4.** Показати всі `device_code`, які зустрічаються у переглядах з `view_count > 20`

In [48]:
query = text("""
SELECT DISTINCT device_code
FROM product_views_log
WHERE view_count > 20
""")

df = pd.read_sql(query, engine)
df

    device_code
0       DVC0219
1       DVC0475
2       DVC0468
3       DVC0024
4       DVC0010
..          ...
435     DVC0118
436     DVC0103
437     DVC0083
438     DVC0030
439     DVC0300

[440 rows x 1 columns]

**Задача 5.** Вивести замовлення між 1 лютого і 1 березня 2024 року.

In [49]:
query = text("""
SELECT *
FROM orders_log
WHERE order_time BETWEEN '2024-02-01' AND '2024-03-01'
""")

df = pd.read_sql(query, engine)
df

    user_uuid  order_time  total_uah
0     USR0270  2024-02-28    2243.89
1     USR0270  2024-02-22     860.55
2     USR0235  2024-02-02    2827.60
3     USR0235  2024-02-18    1622.73
4     USR0213  2024-02-22    2547.48
..        ...         ...        ...
435   USR0255  2024-02-19     851.17
436   USR0037  2024-02-29     214.89
437   USR0037  2024-02-10    1719.10
438   USR0037  2024-02-02    2515.57
439   USR0211  2024-02-17    1236.19

[440 rows x 3 columns]

**Задача 6.** Знайти пристрої без прив’язки до `user_uuid`.