<a href="https://colab.research.google.com/github/cpython-projects/python_da_17_03_26/blob/main/lesson_23_hw.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from sqlalchemy import create_engine, text

In [2]:
DB_USER = "prog_academy_da_157g_user"
DB_PASSWORD = "XTE8IHOEtQZ5GasTkaOjcGMKYTha6LeO"
DB_HOST = "dpg-d8t957gg4nts73da5bg0-a.frankfurt-postgres.render.com"
DB_PORT = "5432"
DB_NAME = "prog_academy_da_157g"

In [3]:
url = f"postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"

In [4]:
engine = create_engine(url)

**Завдання 1.**  

Знайти всі встановлення з `cpi_uah > 30` і платформою **iOS**

In [5]:
query = """
SELECT *
FROM app_sessions
WHERE cpi_uah > 30 AND os_type = 'iOS';
"""

df = pd.read_sql(query, engine)
df

   session_id device_code  first_seen os_type acquisition_channel  cpi_uah
0      S00006     DVC0006  2024-03-02     iOS            Referral    30.56
1      S00010     DVC0010  2024-03-11     iOS            Facebook    32.80
2      S00033     DVC0033  2024-06-08     iOS          Google Ads    37.92
3      S00041     DVC0041  2024-06-27     iOS            Facebook    39.77
4      S00044     DVC0044  2024-02-02     iOS          Google Ads    36.99
..        ...         ...         ...     ...                 ...      ...
58     S00474     DVC0474  2024-06-21     iOS            Referral    38.61
59     S00475     DVC0475  2024-05-15     iOS             Organic    31.31
60     S00480     DVC0480  2024-04-26     iOS            Facebook    38.87
61     S00489     DVC0489  2024-05-29     iOS            Referral    35.08
62     S00499     DVC0499  2024-05-07     iOS          Google Ads    39.78

[63 rows x 6 columns]

**Завдання 2.**  
Знайти **5 найдорожчих** встановлень (найвищий `cpi_uah`)

In [8]:
query = """
SELECT *
FROM app_sessions
ORDER BY cpi_uah DESC
LIMIT 5;
"""

df = pd.read_sql(query, engine)
df

  session_id device_code  first_seen  os_type acquisition_channel  cpi_uah
0     S00108     DVC0108  2024-02-29  Android          Google Ads    40.00
1     S00186     DVC0186  2024-04-14  Android            Referral    39.95
2     S00445     DVC0445  2024-04-27  Android             Organic    39.89
3     S00499     DVC0499  2024-05-07      iOS          Google Ads    39.78
4     S00041     DVC0041  2024-06-27      iOS            Facebook    39.77

**Завдання 3.**  
Порахувати **кількість унікальних пристроїв** у таблиці `product_views_log`

In [10]:
query = """
SELECT COUNT(DISTINCT device_code) AS number_unique_devices
FROM product_views_log;
"""

df = pd.read_sql(query, engine)
df

   number_unique_devices
0                    500

**Завдання 4.**  
Знайти **користувачів**, у яких хоча б **одна покупка перевищує 2000 UAH**

In [13]:
query = """
SELECT DISTINCT user_uuid, total_uah
FROM orders_log
WHERE total_uah > 2000
ORDER BY total_uah DESC
;
"""

df = pd.read_sql(query, engine)
df

    user_uuid  total_uah
0     USR0223    2999.47
1     USR0270    2999.09
2     USR0232    2996.97
3     USR0059    2996.29
4     USR0110    2993.28
..        ...        ...
891   USR0111    2010.90
892   USR0033    2007.42
893   USR0233    2007.20
894   USR0100    2002.57
895   USR0273    2000.71

[896 rows x 2 columns]